name: dashboard_santi
channels:
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python==3.7
  - django
  - djangorestframework
  - django_polymorphic
  - pandas
  - numpy
  - nodejs
  - pyinstaller